### PR TITLE
add CreatePlaneV

### PR DESCRIPTION
**Pull request by sg3des**
add new function for create planes from two points
creating objects of the points - more comfortable and flexible - in this case, both functions(CreatePlaneXY and CreatePlaneXZ) can be replaced.

### CODE REVIEW

**Comment by sg3des** [comment]
damn, I wanted to make two different commits\requests...

**Comment by sg3des** [comment]
These commits, it's just the direction of development, I am trying to do something a little more comfortable, but if you do not think it is suitable, no problem.

**Comment by tbogdala** [comment]
I'll take a look at these tomorrow when I'm home. Sounds like a good idea though.

**Review by tbogdala — CHANGES_REQUESTED** [review]
A test project to render the primitives is a good idea. What I've done for this is to create projects in `examples` for stuff like this. That way you can also use the basic shader in `examples/assets` fairly naturally.

So for this changeset, move the project from `tests` to `examples/primitives` for example. And then consider reusing the `examples/assets/basic.vs|fs` shader.

**Review by tbogdala — APPROVED** [review]
This commit seems to be fine.

**Comment by tbogdala** [comment]
I was wondering if they'd separate this out, but it appears not to. At any rate, the changes to CreatePlaneV are fine, but just reorganize the primitives test example as mentioned above and I'll merge it in.

**Comment by sg3des** [comment]
CreatePlaneV has a flaw - if create diagonal plane, tilt is always the exact same side, i want to add the width of the last argument, CratePlaneV(a,b mgl32.Vec3, width float32). This should be similar to the creation of the line(CreateLineV) but plane...

What do you think about it?

**Comment by tbogdala** [comment]
Well, there's infinite amount of planes that pass through two points because that third point would determine the 'rotation' of the plane along the axis defined by points A and B. So If you wanted better control of the tilt of the plane you'd probably have to do something like that. I'll leave it to you.

I'm looking through that function again and noticed that the normals are always down the +Z axis as well, though. You'll want to calculate that too.

Edit: One way to do this would be to give two points, A and B and then to give the normal you want the plane to face.

**Pull request closed without merging**
